name: critic
description: Timeline view of movie/tv show critiques.

version: 1.2.7+127

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^1.0.1
  animated_bottom_navigation_bar: ^0.3.2
  cached_network_image: ^2.5.0
  cloud_firestore: ^1.0.6
  crypto: ^3.0.0
  cupertino_icons: ^1.0.0
  day_night_switcher: ^0.1.1+1
  equatable: ^2.0.3
  expansion_card: ^0.1.0
  # firebase_analytics: ^6.3.0
  firebase_auth: ^1.1.1
  firebase_auth_web: ^1.0.7
  firebase_core: ^1.0.4
  #firebase_crashlytics: ^0.2.4
  firebase_messaging: ^9.1.2
  flutter_rating_bar: ^4.0.0
  flutter_speed_dial: ^1.2.5
  firebase_storage: ^8.0.4
  flutter_bloc: ^7.3.3
  getwidget: ^1.1.0
  get_it: ^5.0.3
  http: ^0.13.1
  image_cropper: ^1.3.1
  image_downloader: ^0.20.1
  image_picker: ^0.7.4
  image_stack: ^2.0.1
  # integration_test: ^1.0.2+3
  intl: ^0.17.0
  launch_review: ^3.0.1
  material_design_icons_flutter: ^4.0.5755
  new_version: ^0.2.0
  package_info: ^0.4.3+2
  pagination: ^0.1.0
  persistent_bottom_nav_bar: ^4.0.2
  rxdart: ^0.25.0
  share: ^0.6.5+4
  shared_preferences: ^2.0.5
  timeago: ^2.0.29
  tutorial_coach_mark: ^0.5.2
  url_launcher: ^6.0.3
  universal_io: ^1.0.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic
