name: critic
description: Timeline view of movie/tv show critiques.

version: 1.3.9+139

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^1.0.1
  animated_bottom_navigation_bar: ^0.3.2
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.0
  crypto: ^3.0.0
  cupertino_icons: ^1.0.0
  day_night_switcher: ^0.2.0+1
  equatable: ^2.0.3
  expansion_tile_card: ^2.0.0
  firebase_auth: ^3.2.0
  firebase_auth_web: ^3.2.0
  firebase_core: ^1.10.5
  firebase_messaging: ^11.1.0
  fluid_bottom_nav_bar: ^1.3.0
  flutter_local_notifications: ^9.2.0
  flutter_rating_bar: ^4.0.0
  flutter_speed_dial: ^4.6.6
  firebase_storage: ^10.1.0
  flutter_bloc: ^7.3.3
  freezed_annotation:
  get: ^4.6.1
  getwidget: ^2.0.4
  get_it: ^7.2.0
  google_sign_in: ^5.2.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.1
  http: ^0.13.1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  image_stack: ^2.0.1
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  launch_review: ^3.0.1
  material_design_icons_flutter: ^5.0.6295
  new_version: ^0.2.0
  package_info: ^2.0.2
  pagination_view: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  rxdart: ^0.27.2
  sign_in_with_apple: ^3.3.0
  share: ^2.0.4
  shared_preferences: ^2.0.5
  stream_feed: ^0.5.0
  timeago: ^3.1.0
  tutorial_coach_mark: ^1.1.1
  url_launcher: ^6.0.3
  universal_io: ^2.0.4
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^0.15.1+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic
