name: critic
description: Timeline view of movie/tv show critiques.

version: 1.1.5+115

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^0.1.7
  bottom_navy_bar: ^5.6.0
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  day_night_switcher: ^0.1.1+1
  equatable: ^1.2.5
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.4+1
  firebase_auth_web: ^0.3.2+3
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_messaging: ^7.0.3
  flutter_speed_dial: ^1.2.5
  firebase_storage: ^5.2.0
  flutter_bloc: ^6.1.1
  getwidget: ^1.1.0
  get_it: ^5.0.3
  http: ^0.12.2
  image_cropper: ^1.3.1
  image_downloader: ^0.20.1
  image_picker: ^0.6.7+15
  integration_test: ^1.0.0
  intl: ^0.16.1
  material_design_icons_flutter: ^4.0.5755
  package_info: ^0.4.3+2
  pagination: ^0.1.0
  rxdart: ^0.25.0
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  timeago: ^2.0.29
  tutorial_coach_mark: ^0.5.2
  url_launcher: ^5.7.10
  universal_io: ^1.0.1
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic
