name: critic
description: A new Flutter project.

version: 1.0.2+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  algolia: ^0.1.7
  bottom_navy_bar: ^5.4.0
  #bubble_bottom_bar: ^1.2.0
  carousel_slider: ^1.4.1
  #cached_network_image: ^2.0.0
  cloud_firestore: ^0.13.4+2
  dash_chat: ^1.0.16
  device_info: ^0.4.2+1
  equatable: ^1.1.1
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.4+3
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.3
  flappy_search_bar: ^1.7.2
  flutter_bloc: ^4.0.0
  get_it: ^4.0.1
  http: ^0.12.0+4 
  package_info: ^0.4.0+16
  pagination: ^0.1.0
  image_cropper: ^1.2.1
  image_downloader: ^0.19.2
  image_picker: ^0.6.3+4
  intl: ^0.16.1
  material_design_icons_flutter: ^4.0.5045
  rxdart: ^0.24.0
  simple_animations: ^1.3.11
  share: ^0.6.3+6
  timeago: ^2.0.26
  url_launcher: ^5.4.2

flutter:

  uses-material-design: true

  assets:
   - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic